# -*- coding: utf-8 -*-
"""SOC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BO9c1ajTEcWWcToxGm87T-kPrvrGuP4P
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/pytorch/examples.git
# %cd examples/fast_neural_style

!pip install -r requirements.txt

from google.colab import files
uploaded = files.upload()

!python download_saved_models.py

!python neural_style/neural_style.py eval \
  --content-image image.jpg \
  --model saved_models/mosaic.pth \
  --output-image output.jpg

from IPython.display import Image
Image(filename="output.jpg")

files.download("output.jpg")